# Climate Vulnerability Tool Config File

# Model Section Switches
switches:
  # If running from scratch using only the raw input files these switches should all be true
  run_data_cleaning: true
  run_functional_rules: true
  run_layering: true

  # Infrastructure switches 
  all_roads: true
  noham_roads: true

  passenger_rail: true
  freight_rail: true

  airports: false
  bus_stops: false
  petrol_stations: false
  charging_sites: false
  national_cycle_network: true
  train_stations: true
  tram_stations: true
  rapid_transport_stations: false
  ferry_terminals: false
  bus_coach_stations: false
  tram_network: true
  rapid_transport_network: false

  # Hazard switches
  extreme_weather: true
  flooding: true
  ground_stability: false
  coastal_erosion: false


  # True if the direct flooding overlay should be computed (this takes 2-3 Months to run for whole North), 
  compute_flooding_overlay: false

  # True if the raw NoHAM h5 files need to be extracted from zip file
  noham_zip_extract: false



parameters:
  # Name of Sub-National Transport Body to run the tool for (this must exactly match the name in the boundary data)
  # Should be empty if running for CA rather than STB
  # Options include: 'Transport for the North' (model only works for North of England at present)
  stb:

  # Name of Combined Authority to run the tool for (this must exactly match the name in the boundary data)
  # Should be empty if running for STB rather than CA
  # Options include: 'Greater Manchester', 'South Yorkshire', 'West Yorkshire', 'Liverpool City Region', 'Tees Valley', 
  #                  'York and North Yorkshire', 'North East', 'Hull and East Yorkshire', 'Lancashire'
  ca: South Yorkshire


###### FILE PATHS ######

paths:
  root: D:/Climate Vulnerability Tool/Localisation/v1/Data # This is the root of any outputs of the model
  raw_input: D:/Climate Vulnerability Tool/Localisation/v1/Data/raw input

other_input:
  # If using a specific boundary file rather than from OpenGeographyPortal, provide the path here, otherwise leave empty
  boundary_path:
  stb_path: Other/STB_2023/STB_Boundary_2023.shp
  ca_path: Other/Combined_Authorities_December_2025_Boundaries_EN_BFC.gpkg

infrastructure:
  road:
    os_road:
      zip_path: Infrastructure/Road/oproad_gpkg_gb.zip
      file_path: Data/oproad_gb.gpkg
      output_path: 
    noham:
      year: 2023
      file_path: Infrastructure/Road/NoHAM 2023/NoHAM_Decarb_DM_Core_2023_carbon.shp
  rail:
    rail_links: Infrastructure/Rail/OS Rail Network/TfN_Area_tfn_ntwk_railwaylink.gpkg
  other:
    bus_stops:
      north_east: Infrastructure/Other/Bus Stops/bus_stops_ne.csv
      north_west: Infrastructure/Other/Bus Stops/bus_stops_nw.csv
      yorkshire: Infrastructure/Other/Bus Stops/bus_stops_ys.csv
    ncn_sustrans: Infrastructure/Other/NCN Sustrans/National_Cycle_Network_Public.shp
    os_mmrn: Infrastructure/Other/OS Multi-Modal Routing Network/OSMulti-modalRoutingNetwork.gpkg
    poi_uk:
      zip_path: Infrastructure/Other/poi_uk.zip
      file_path: poi_uk.gpkg
      output_path: 
    zapmap: Infrastructure/Other/ZapMap/ZapMap Site Devices.csv
    airports: Infrastructure/Other/TfN Airports/tfn_airports.shp

hazards:
  coastal_erosion:
    zip_path: Hazards/Coastal Erosion/National_Coastal_Erosion_Risk_Mapping_NCERM_National_2024.gpkg.zip
    file_path: National_Coastal_Erosion_Risk_Mapping_NCERM_National_2024.gpkg
    output_path: 
  extreme_weather:
    max_temp_summer: Hazards/Extreme Weather/Extreme Heat/Summer_Maximum_Temperature_Change_Projections_12km.gpkg
    extreme_summer_days: Hazards/Extreme Weather/Extreme Heat/Annual_Count_of_Extreme_Summer_Days_Projections_12km.gpkg
    hot_days: Hazards/Extreme Weather/Extreme Heat/Annual_Count_of_Hot_Days_Projections_12km.gpkg
    min_temp_winter: Hazards/Extreme Weather/Extreme Cold/Winter_Minimum_Temperature_Change_Projections_12km.gpkg
    frost_days: Hazards/Extreme Weather/Extreme Cold/Annual_Count_of_Frost_Days_Projections_12km.gpkg
    icing_days: Hazards/Extreme Weather/Extreme Cold/Annual_Count_of_Icing_Days_Projections_12km.gpkg
    drought_index: Hazards/Extreme Weather/Drought/Drought_Severity_Index_12_Month_Accumulations.gpkg
    precip_summer: Hazards/Extreme Weather/Drought/Summer_Precipitation_Change_Projections_12km.gpkg
    wind_speed:
      1990_2000: Hazards/Extreme Weather/Storm/wsgmax10m_rcp85_land-cpm_uk_5km_01_day_19901201-20001130.nc
      2070_2080: Hazards/Extreme Weather/Storm/wsgmax10m_rcp85_land-cpm_uk_5km_01_day_20701201-20801130.nc
    rain_days: Hazards/Extreme Weather/Storm/Annual_Count_of_10mm_Rain_Days_1991_2020.gpkg
    wdr_index: Hazards/Extreme Weather/Storm/Annual_Index_of_Wind_Driven_Rain_Projections_5km.gpkg
    precip_winter: Hazards/Extreme Weather/Storm/Winter_Precipitation_Change_Projections_12km.gpkg
  flooding:
    rivers_sea: F:/1. Carbon Core/15. Climate Vulnerability/Phase 2/Data/raw inputs/Hazards/Flooding/RoFRS
    surface_water: F:/1. Carbon Core/15. Climate Vulnerability/Phase 2/Data/raw inputs/Hazards/Flooding/RoFSW
  ground_stability:
    geo_shrink_swell:
      "2030": Hazards/Ground Stability/GeoClimateUKCP18OpenData/GeoclimateUKCP18_Open/GeoClimateUKCP18_ShrinkSwell_2030_Average_Open.shp
      "2070": Hazards/Ground Stability/GeoClimateUKCP18OpenData/GeoclimateUKCP18_Open/GeoClimateUKCP18_ShrinkSwell_2070_Average_Open.shp
    geosure:
      zip_path: Hazards/Ground Stability/GB_Hex_5km_GeoSure_All.zip
      file_path: GB_Hex_5km_GeoSure_All_V8.gpkg
      output_path: 

impact:
  freight_demand: Impact/Freight/rail_freight_network_demand.gpkg
  noham_demand:
    zip_path: Impact/NoHAM Link Flows/input h5s.7z
    file_path: 
    output_path: Impact/NoHAM Link Flows/h5 files
  noham_years:
    - 2023
    - 2048





